config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :greetings
  namespace :admin do
    resources :users
    resources :services
    resources :notifications
    resources :announcements

    root to: 'users#index'
  end
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'greetings#index'
end

app/models/greeting.rb
# frozen_string_literal: true

class Greeting < ApplicationRecord
  validates :name, presence: true
  validates :message, presence: true
end

app/controllers/greetings_controller.rb
# frozen_string_literal: true

class GreetingsController < ApplicationController
  before_action :set_greeting, only: %i[show edit update destroy]

  # GET /greetings or /greetings.json
  def index
    @greetings = Greeting.all
  end

  # GET /greetings/1 or /greetings/1.json
  def show; end

  # GET /greetings/new
  def new
    @greeting = Greeting.new
  end

  # GET /greetings/1/edit
  def edit; end

  # POST /greetings or /greetings.json
  def create
    @greeting = Greeting.new(greeting_params)

    respond_to do |format|
      if @greeting.save
        format.html { redirect_to root_path, notice: 'Greeting was successfully created.' }
        format.json { render :show, status: :created, location: @greeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /greetings/1 or /greetings/1.json
  def update
    respond_to do |format|
      if @greeting.update(greeting_params)
        format.html { redirect_to greeting_url(@greeting), notice: 'Greeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @greeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /greetings/1 or /greetings/1.json
  def destroy
    @greeting.destroy

    respond_to do |format|
      format.html { redirect_to greetings_url, notice: 'Greeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_greeting
    @greeting = Greeting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def greeting_params
    params.require(:greeting).permit(:name, :message)
  end
end

app/helpers/greetings_helper.rb
# frozen_string_literal: true

module GreetingsHelper
  def gravatarized_url(name)
    hash = Digest::MD5.hexdigest(name)
    "https://www.gravatar.com/avatar/#{hash}?d=wavatar"
  end
end

app/views/greetings/_form.html.erb
<div class="card">
  <div class="card-body">
  <h5 class="card-title">Send me a message!</h5>
  <%= form_with(model: greeting, local: true) do |form| %>
    <% if greeting.errors.any? %>
      <div id="error_explanation">
  <h2>
  <%= pluralize(greeting.errors.count, "error") %>
  prohibited this greeting from being saved:
  </h2>
  <ul>
  <% greeting.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  </div>
      <% end %>
    <div class="form-group mt-3">
  <%= form.text_field :name, placeholder: "Name", class: "form-control" %>
    </div>
      <div class="form-group mt-3">
        <%= form.text_area :message, placeholder: "Message", class: "form-control" %>
      </div>
    <div class="actions mt-3">
<%= form.submit "Send", class: "btn btn-outline-dark" %>
    </div>
    <% end %>
  </div>
</div>

app/views/greetings/_greeting.html.erb
<div id="<%= dom_id greeting %>">
  <p>
    <strong>Name:</strong>
    <%= greeting.name %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= greeting.message %>
  </p>

</div>

app/views/greetings/edit.html.erb
<h1>Editing greeting</h1>

<%= render "form", greeting: @greeting %>

<br>

<div>
  <%= link_to "Show this greeting", @greeting %> |
  <%= link_to "Back to greetings", greetings_path %>
</div>

app/views/greetings/index.html.erb
<p id="notice"><%= notice %></p>
<br/>
<% @greetings.each do |greeting| %>
  <div class="media">
    <img src="<%= gravatarized_url(greeting.name) %>"
         class="align-self-start mr-3">
    <div class="media-body">
      <br />
      <h5 class="mt-0"><%= greeting.name %></h5>
      <br />
      <%= greeting.message %>
    </div>
  </div>
  <br/>
<% end %>

app/views/greetings/new.html.erb
<div class="mt-4">
<h1>New greeting</h1>

<%= render "form", greeting: @greeting %>

<br>

<div>
  <%= link_to "Back to greetings", greetings_path %>
</div>
</div>

app/views/greetings/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="mt-4">
<%= render @greeting %>
<div>
  <%= link_to "Edit this greeting", edit_greeting_path(@greeting) %> |
  <%= link_to "Back to greetings", greetings_path %>
  <%= button_to "Destroy this greeting", @greeting, method: :delete %>
</div>
</div>